<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    //Datos de prueba para la tabla PRODUCTO
    public function run(): void
    {
        DB::table('PRODUCTO')->insert([
            [
                'categoria' => 'anillo',
                'nombre' => 'Anillo Oro Blanco Diamante',
                'marca' => 'Cartier',
                'descripcion' => 'Anillo de oro blanco con pequeño diamante central',
                'precio' => 499.99,
                'genero' => 'mujer',
                'color' => 'blanco',
                'talla' => '16',
                'ruta_grabado' => 'grabados/anillo_oro_blanco.png',
                'material' => 'oro blanco',
                'peso' => 4.5,
                'stock' => 3,
                'id_detalles_pedido' => null,
            ],
            [
                'categoria' => 'anillo',
                'nombre' => 'Anillo Acero Negro',
                'marca' => 'Armani',
                'descripcion' => 'Anillo de acero inoxidable negro mate',
                'precio' => 49.90,
                'genero' => 'hombre',
                'color' => 'negro',
                'talla' => '20',
                'ruta_grabado' => 'grabados/anillo_acero_negro.png',
                'material' => 'acero',
                'peso' => 6.3,
                'stock' => 10,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'pulsera',
                'nombre' => 'Pulsera Cadena Plata',
                'marca' => 'Pandora',
                'descripcion' => 'Pulsera de cadena fina de plata',
                'precio' => 59.00,
                'genero' => 'mujer',
                'color' => 'plata',
                'talla' => 'S',
                'ruta_grabado' => 'grabados/pulsera_cadena.png',
                'material' => 'plata',
                'peso' => 7.8,
                'stock' => 14,
                'id_detalles_pedido' => null,
            ],
            [
                'categoria' => 'pulsera',
                'nombre' => 'Pulsera Deportiva Silicona',
                'marca' => 'Nike',
                'descripcion' => 'Pulsera ligera de silicona resistente al agua',
                'precio' => 15.99,
                'genero' => 'unisex',
                'color' => 'azul',
                'talla' => 'L',
                'ruta_grabado' => 'grabados/pulsera_silicona.png',
                'material' => 'silicona',
                'peso' => 5.2,
                'stock' => 30,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'pendiente',
                'nombre' => 'Pendientes Aro Plata',
                'marca' => 'Tous',
                'descripcion' => 'Pendientes tipo aro de plata lisa',
                'precio' => 35.00,
                'genero' => 'mujer',
                'color' => 'plata',
                'talla' => null,
                'ruta_grabado' => 'grabados/pendientes_aro_plata.png',
                'material' => 'plata',
                'peso' => 5.0,
                'stock' => 18,
                'id_detalles_pedido' => null,
            ],
            [
                'categoria' => 'pendiente',
                'nombre' => 'Pendientes Minimal Dorados',
                'marca' => 'Swarovski',
                'descripcion' => 'Pendientes pequeños dorados de estilo minimalista',
                'precio' => 29.95,
                'genero' => 'mujer',
                'color' => 'dorado',
                'talla' => null,
                'ruta_grabado' => 'grabados/pendientes_minimal.png',
                'material' => 'acero',
                'peso' => 3.6,
                'stock' => 22,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'collar',
                'nombre' => 'Collar Cruz Plata',
                'marca' => 'Lotus',
                'descripcion' => 'Collar de plata con colgante de cruz',
                'precio' => 44.50,
                'genero' => 'unisex',
                'color' => 'plata',
                'talla' => '50cm',
                'ruta_grabado' => 'grabados/collar_cruz.png',
                'material' => 'plata',
                'peso' => 11.4,
                'stock' => 9,
                'id_detalles_pedido' => null,
            ],
            [
                'categoria' => 'collar',
                'nombre' => 'Collar Perlas Elegante',
                'marca' => 'Majorica',
                'descripcion' => 'Collar clásico de perlas cultivadas',
                'precio' => 120.00,
                'genero' => 'mujer',
                'color' => 'blanco',
                'talla' => '42cm',
                'ruta_grabado' => 'grabados/collar_perlas.png',
                'material' => 'perla',
                'peso' => 18.9,
                'stock' => 5,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'anillo',
                'nombre' => 'Anillo Plata Grabado',
                'marca' => 'Lotus',
                'descripcion' => 'Anillo de plata con grabado interior personalizable',
                'precio' => 55.00,
                'genero' => 'unisex',
                'color' => 'plata',
                'talla' => '19',
                'ruta_grabado' => 'grabados/anillo_grabado.png',
                'material' => 'plata',
                'peso' => 4.1,
                'stock' => 12,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'pulsera',
                'nombre' => 'Pulsera Acero Dorado',
                'marca' => 'Guess',
                'descripcion' => 'Pulsera rígida de acero dorado',
                'precio' => 49.99,
                'genero' => 'mujer',
                'color' => 'dorado',
                'talla' => 'M',
                'ruta_grabado' => 'grabados/pulsera_acero_dorado.png',
                'material' => 'acero',
                'peso' => 13.6,
                'stock' => 11,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'pendiente',
                'nombre' => 'Pendientes Estrella',
                'marca' => 'Pandora',
                'descripcion' => 'Pendientes pequeños con forma de estrella',
                'precio' => 27.50,
                'genero' => 'mujer',
                'color' => 'plata',
                'talla' => null,
                'ruta_grabado' => 'grabados/pendientes_estrella.png',
                'material' => 'plata',
                'peso' => 2.9,
                'stock' => 25,
                'id_detalles_pedido' => null,
            ],

            [
                'categoria' => 'collar',
                'nombre' => 'Collar Hombre Acero',
                'marca' => 'Armani',
                'descripcion' => 'Collar de acero inoxidable para hombre',
                'precio' => 65.00,
                'genero' => 'hombre',
                'color' => 'negro',
                'talla' => '55cm',
                'ruta_grabado' => 'grabados/collar_acero_hombre.png',
                'material' => 'acero',
                'peso' => 20.3,
                'stock' => 6,
                'id_detalles_pedido' => null,
            ]
        ]);
    }
}
